### ISSUE TITLE
Sync data

### ISSUE THREAD

**Issue by tetuaoro** [sqwid-app/sqwid-backend#2]
Hi sqwid team,

I have sent you an email but have not received a reply. I used the `wrap1155` function in sqwid1155 contract and `createItem` function in sqwidMarketPlace. When will the synchronize function from the backend be available ?

**Comment by andithemudkip** [comment]
Hello! We don't officially support wrapping external tokens yet so there isn't really a flow set up to do that easily.

I see you've already wrapped them in the contracts, technically the last step would be sending a request to the `/create/collectible/verify` endpoint of the backend with the itemId from the marketplace, a collection ID of a collection you own, and using a valid jwt as bearer token that you get after authenticating
You can see how we do it in the frontend [here](https://github.com/sqwid-app/sqwid-client/blob/master/src/utils/createCollectible.js#L184)

However, I want to be **super clear** that I'm not sure this will work if the metadata doesn't follow our [internal standard](https://ipfs.io/ipfs/QmWQw5FtK8N4BhB5CY6LbNKe6KAJRo1hkzT7vDWMmeuy49), as this is **not something we currently support**
